---

services:
  dsmr-client:
    image: ${DOCKER_IMAGE:-dsmr_client}
    build: .
    restart: on-failure
    environment:
      - TCP_HOST
      - TCP_PORT=1234
      - INFLUXDB_BUCKET=dsmr
      - INFLUXDB_ORG=dsmr
      - INFLUXDB_TOKEN=dsmr-token
      - INFLUXDB_URL=http://influxdb:8086
    develop:
      watch:
        - action: sync+restart
          path: ./dsmr_client
          target: /app/dsmr_client
        - action: rebuild
          path: ./pyproject.toml
    depends_on:
      influxdb:
        condition: service_healthy

  influxdb:
    image: influxdb:2.7
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=dsmr
      - DOCKER_INFLUXDB_INIT_PASSWORD=dsmr-password
      - DOCKER_INFLUXDB_INIT_ORG=dsmr
      - DOCKER_INFLUXDB_INIT_BUCKET=dsmr
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=dsmr-token
      - DOCKER_INFLUXDB_INIT_RETENTION=3d
      - INFLUXD_REPORTING_DISABLED=true
    ports:
      - 8086:8086
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - ./influxdb/scripts:/docker-entrypoint-initdb.d
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    links:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - INFLUXDB_BUCKET=dsmr
      - INFLUXDB_ORG=dsmr
      - INFLUXDB_TOKEN=dsmr-token
    ports:
      - 3000:3000
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana


volumes:
  influxdb_data:
  grafana_data:

