version: "3.8"

services:
  dsmr_client:
    build: .
    image: dsmr_client
    environment:
      - TCP_HOST
      - TCP_PORT
      - INFLUXDB_BUCKET
      - INFLUXDB_ORG
      - INFLUXDB_TOKEN
      - INFLUXDB_URL=http://influxdb:8086
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.7
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=dsmr
      - DOCKER_INFLUXDB_INIT_PASSWORD=dsmr-password
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    ports:
      - 8086:8086
    healthcheck:
      test: ["CMD", "influxdb", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    links:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - INFLUXDB_BUCKET
      - INFLUXDB_ORG
      - INFLUXDB_TOKEN
    ports:
      - 3000:3000
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana


volumes:
  influxdb_data:
  grafana_data:

