version: "3.8"

services:
  influxdb:
    image: influxdb:2.7
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=dsmr
      - DOCKER_INFLUXDB_INIT_PASSWORD=dsmr-password
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    ports:
      - 127.0.0.1:8086:8086
    volumes:
      - influx_data:/var/lib/influxdb2

volumes:
  influx_data:
