apiVersion: 1

datasources:
  - name: Test
    type: influxdb
    uid: df63a307-9d9c-44f3-8e28-0982ff461c22
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    editable: false

