name: Push
on: push

jobs:
  static-analysis:
    name: Static analysis
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python-version }} 
          poetry install
      - name: Formatting
        run: poetry run ruff format --check
      - name: Linting
        run: poetry run ruff check
      - name: Typing
        run: poetry run mypy .
  