name: Push

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: 3.12
          enable-cache: true
      - name: Ruff format
        run: uv run ruff format --check
      - name: Ruff format
        run: uv run ruff check
      - name: Ruff format
        run: uv run mypy .
