name: Push
on: push

jobs:
  static-analysis:
    name: Static analysis
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check version:
        run: poetry run python -V

      # - name: Install dependencies
      #   run: poetry install
      # - name: Run black
      #   run: poetry run black . --check
      # - name: Run isort
      #   run: poetry run isort . --check-only
      # - name: Run mypy
      #   run: poetry run mypy .
